version: '3.4'

services:
  web:
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - ./config.json:/docker-entrypoint.d/config.json
      - .:/www/
    ports:
      - '8080:8080'
